// Import the UI elements
var UI = require('ui');
var Vector2 = require('vector2');
var Accel = require('ui/accel');
Accel.init();
// Create a simple Card
var card = new UI.Window({
  title: 'Franponator',
});

var textfield = new UI.Text({
  position: new Vector2(0, 35),
  size: new Vector2(144, 30),
  font: 'gothic-28',
  text :'Franponator',
  textAlign: 'center'
});
card.add(textfield);

Accel.on('tap', function() {
  
var textA = new [].constructor(68);
  textA[0] = 'Bonjour';
  textA[1] = 'Cafe';
  textA[2] = 'Vivre';
  textA[3] = 'Champ';
  textA[4] = 'Pain';
  textA[5] = 'Cul';
  textA[6] = 'Rue';
  textA[7] = 'Jus';
  textA[8] = 'Pied';
  textA[9] = 'Lait';
  textA[10] = 'Champ';
  textA[11] = 'Crepes';
  textA[12] = 'Pierrot';
  textA[13] = 'Cle';
  textA[14] = 'Couturier';
  textA[15] = 'Decadence';
  textA[16] = 'Pain';
  textA[17] = 'Jouir';
  textA[18] = 'Musee';
  textA[19] = 'Jus';
  textA[20] = 'Belle';
  textA[21] = 'Marchand';
  textA[22] = 'Salon';
  textA[23] = 'Promenades';
  textA[24] = 'Bijou';
  textA[25] = 'Famille';
  textA[26] = 'Creme';
  textA[27] = 'La devise';
  textA[28] = 'Un gateau';
  textA[29] = 'Maison';
  textA[30] = 'Cahier';
  textA[31] = 'Saveur';
  textA[32] = 'Le Coeur';
  textA[33] = 'La vie';
  textA[34] = 'Cafe Chez';
  textA[35] = 'Bois';
  textA[36] = 'Marche';
	textA[37] = 'Bistrot';
  textA[38] = 'Caprice';
  textA[39] = 'Beurre';
  textA[40] = 'Bouillon';
  textA[41] = 'Cochon';
  textA[42] = 'Boite';
  textA[43] = 'Barbara';
  textA[44] = 'Mobylette';
  textA[45] = 'Bicyclette';
  textA[46] = 'Cigare';
  textA[47] = 'Parfum';
  textA[48] = 'Liqueur';
  textA[49] = 'Chocolat';
  textA[50] = 'Fleur';
  textA[51] = 'Violette';
  textA[52] = 'Rose';
  textA[53] = 'Pantalon';
  textA[54] = 'Amour';
  textA[55] = 'Pipe';
  textA[56] = 'Lait';
  textA[57] = 'Boule';
  textA[58] = 'Ancule';
  textA[59] = 'Pipi';
  textA[60] = 'Soldes';
  textA[61] = 'Comme ça';
  textA[62] = 'Madelaine';
  textA[63] = 'Bien';
  textA[64] = 'Beau';
  textA[65] = 'Partouze';
  textA[66] = 'Chie';
	
	var textB = new [].constructor(15);
  
  textB[0] = 'a';
  textB[1] = 'de';
  textB[2] = 'pour';
  textB[3] = 'sans';
  textB[4] = 'du';
  textB[5] = 'de';
  textB[6] = 'en';
  textB[7] = 'la';
  textB[8] = 'par';
  textB[9] = 'vers';
  textB[10] = 'dans';
  textB[11] = 'ce';
  textB[12] = 'avec';
  textB[13] = 'sous';
	
	var textC = new [].constructor(63);
  
  textC[0] = 'buisson';
  textC[1] = 'herbe';
  textC[2] = 'cocorico';
  textC[3] = 'pierrot';
  textC[4] = 'peau';
  textC[5] = 'rendez-vous';
  textC[6] = 'Chocolat';
  textC[7] = 'delicieux';
  textC[8] = 'bijou';
  textC[9] = 'coeur';
  textC[10] = 'meure';
  textC[11] = 'legumes';
  textC[12] = 'crayon';
  textC[13] = 'Paris';
  textC[14] = 'gouter';
  textC[15] = 'tete';
  textC[16] = 'Pluis Pluis';
  textC[17] = 'poule';
  textC[18] = 'girafe';
  textC[19] = 'chie';
  textC[20] = 'jour';
  textC[21] = 'la creme';
  textC[22] = 'bonheur';
  textC[23] = 'soin';
  textC[24] = 'La Mille';
  textC[25] = 'Les Anges';
  textC[26] = 'rose';
  textC[27] = 'Gare';
  textC[28] = 'Crie';
  textC[29] = 'pepere';
  textC[30] = 'Boulogne';
  textC[31] = 'metro';
  textC[32] = 'Hasard';
  textC[33] = 'la papa';
  textC[34] = 'salade';
  textC[35] = 'argent';
  textC[36] = 'presentation';
  textC[37] = 'table';
  textC[38] = 'cachette';
  textC[39] = 'social';
  textC[40] = 'moustache';
  textC[41] = 'balais';
  textC[42] = 'casquette'; 
  textC[43] = 'beret';
  textC[44] = 'baguette';
  textC[45] = 'croissant';
  textC[46] = 'pain';
  textC[47] = 'coin coin';
  textC[48] = 'saucisse';
  textC[49] = 'cassoulet';
  textC[50] = 'bouillabaisse';
  textC[51] = 'tete-de-veau';
  textC[52] = 'pot-au-feu';
  textC[53] = 'provence';
  textC[54] = 'Montparnasse';
  textC[55] = 'Saint-Germain';
  textC[56] = 'Ourse';
  textC[57] = 'bite';
  textC[58] = 'Cancer';
  textC[59] = 'Chatte';
  textC[60] = 'Pine';
  textC[61] = 'Parler';
  
	var ligneA = textA[Math.floor(Math.random()*(textA.length-1))];
	var ligneB = textB[Math.floor(Math.random()*(textB.length-1))];
	var ligneC = textC[Math.floor(Math.random()*(textC.length-1))];
  
  textfield.text(ligneA+" "+ligneB+" "+ligneC);
});


card.on('click', function() {
  
var textA = new [].constructor(68);
  
  textA[0] = 'Bonjour';
  textA[1] = 'Cafe';
  textA[2] = 'Vivre';
  textA[3] = 'Champ';
  textA[4] = 'Pain';
  textA[5] = 'Cul';
  textA[6] = 'Rue';
  textA[7] = 'Jus';
  textA[8] = 'Pied';
  textA[9] = 'Lait';
  textA[10] = 'Champ';
  textA[11] = 'Crepes';
  textA[12] = 'Pierrot';
  textA[13] = 'Cle';
  textA[14] = 'Couturier';
  textA[15] = 'Decadence';
  textA[16] = 'Pain';
  textA[17] = 'Jouir';
  textA[18] = 'Musee';
  textA[19] = 'Jus';
  textA[20] = 'Belle';
  textA[21] = 'Marchand';
  textA[22] = 'Salon';
  textA[23] = 'Promenades';
  textA[24] = 'Bijou';
  textA[25] = 'Famille';
  textA[26] = 'Creme';
  textA[27] = 'La devise';
  textA[28] = 'Un gateau';
  textA[29] = 'Maison';
  textA[30] = 'Cahier';
  textA[31] = 'Saveur';
  textA[32] = 'Le Coeur';
  textA[33] = 'La vie';
  textA[34] = 'Cafe Chez';
  textA[35] = 'Bois';
  textA[36] = 'Marche';
	textA[37] = 'Bistrot';
  textA[38] = 'Caprice';
  textA[39] = 'Beurre';
  textA[40] = 'Bouillon';
  textA[41] = 'Cochon';
  textA[42] = 'Boite';
  textA[43] = 'Barbara';
  textA[44] = 'Mobylette';
  textA[45] = 'Bicyclette';
  textA[46] = 'Cigare';
  textA[47] = 'Parfum';
  textA[48] = 'Liqueur';
  textA[49] = 'Chocolat';
  textA[50] = 'Fleur';
  textA[51] = 'Violette';
  textA[52] = 'Rose';
  textA[53] = 'Pantalon';
  textA[54] = 'Amour';
  textA[55] = 'Pipe';
  textA[56] = 'Lait';
  textA[57] = 'Boule';
  textA[58] = 'Ancule';
  textA[59] = 'Pipi';
  textA[60] = 'Soldes';
  textA[61] = 'Comme ca';
  textA[62] = 'Madelaine';
  textA[63] = 'Bien';
  textA[64] = 'Beau';
  textA[65] = 'Partouze';
  textA[66] = 'Chie';
	
	var textB = new [].constructor(15);
  
  textB[0] = 'a';
  textB[1] = 'de';
  textB[2] = 'pour';
  textB[3] = 'sans';
  textB[4] = 'du';
  textB[5] = 'de';
  textB[6] = 'en';
  textB[7] = 'la';
  textB[8] = 'par';
  textB[9] = 'vers';
  textB[10] = 'dans';
  textB[11] = 'ce';
  textB[12] = 'avec';
  textB[13] = 'sous';
	
	var textC = new [].constructor(63);
  
  textC[0] = 'buisson';
  textC[1] = 'herbe';
  textC[2] = 'cocorico';
  textC[3] = 'pierrot';
  textC[4] = 'peau';
  textC[5] = 'rendez-vous';
  textC[6] = 'Chocolat';
  textC[7] = 'delicieux';
  textC[8] = 'bijou';
  textC[9] = 'coeur';
  textC[10] = 'meure';
  textC[11] = 'legumes';
  textC[12] = 'crayon';
  textC[13] = 'Paris';
  textC[14] = 'gouter';
  textC[15] = 'tete';
  textC[16] = 'Pluis Pluis';
  textC[17] = 'poule';
  textC[18] = 'girafe';
  textC[19] = 'chie';
  textC[20] = 'jour';
  textC[21] = 'la creme';
  textC[22] = 'bonheur';
  textC[23] = 'soin';
  textC[24] = 'La Mille';
  textC[25] = 'Les Anges';
  textC[26] = 'rose';
  textC[27] = 'Gare';
  textC[28] = 'Crie';
  textC[29] = 'pepere';
  textC[30] = 'Boulogne';
  textC[31] = 'metro';
  textC[32] = 'Hasard';
  textC[33] = 'la papa';
  textC[34] = 'salade';
  textC[35] = 'argent';
  textC[36] = 'presentation';
  textC[37] = 'table';
  textC[38] = 'cachette';
  textC[39] = 'social';
  textC[40] = 'moustache';
  textC[41] = 'balais';
  textC[42] = 'casquette'; 
  textC[43] = 'beret';
  textC[44] = 'baguette';
  textC[45] = 'croissant';
  textC[46] = 'pain';
  textC[47] = 'coin coin';
  textC[48] = 'saucisse';
  textC[49] = 'cassoulet';
  textC[50] = 'bouillabaisse';
  textC[51] = 'tete-de-veau';
  textC[52] = 'pot-au-feu';
  textC[53] = 'provence';
  textC[54] = 'Montparnasse';
  textC[55] = 'Saint-Germain';
  textC[56] = 'Ourse';
  textC[57] = 'bite';
  textC[58] = 'Cancer';
  textC[59] = 'Chatte';
  textC[60] = 'Pine';
  textC[61] = 'Parler';
  
	var ligneA = textA[Math.floor(Math.random()*(textA.length-1))];
	var ligneB = textB[Math.floor(Math.random()*(textB.length-1))];
	var ligneC = textC[Math.floor(Math.random()*(textC.length-1))];
  
  textfield.text(ligneA+" "+ligneB+" "+ligneC);
});

// Display to the user
card.show();
